service: news-aggregator

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment:
    DYNAMODB_TABLE: onlynews-items
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    NewsItems:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  cron:
    timeout: 30
    handler: cron.run
    events:
      - schedule: rate(10 minutes)
      - http:
           path: /scrap
           method: GET

  tweets:
    timeout: 30
    handler: tweets.get
    events:
      - schedule: rate(5 minutes)
      - http:
           path: /tweets
           method: GET

  list:
    handler: list.list
    events:
      - http:
          path: list
          method: GET
          cors: true